package rules;
import com.study.droolscore.domain.Food;
import java.util.List;
import com.study.droolscore.domain.ShoppingCar;
import java.math.BigDecimal;
//这里是第一次演示用的
//rule "plan-A" when
//      $shoppingCar:ShoppingCar($foods:buyList)
//      List(size==3) from collect(Food((["巨无霸","可乐","薯条"] contains name)) from $foods)
//  then
//    $shoppingCar.setTotalMoney(17D);
//    $shoppingCar.getRules().add(drools.getRule().getName());
//end

rule "没有套餐"
  salience -1
  no-loop true
  lock-on-active true
  when
       $shoppingCar:ShoppingCar($foods:leftList)
       $money:BigDecimal() from accumulate(Food($price:price) from $foods,sum($price))
  then
        $foods.removeAll($foods);
        BigDecimal $totalMoney = $shoppingCar.getTotalMoney().add($money);
        $shoppingCar.setTotalMoney($totalMoney);
        $shoppingCar.getRules().add(drools.getRule().getName());
        retract($shoppingCar);
end
