package rules;
import com.study.droolscore.domain.Food;
import java.util.List;
import com.study.droolscore.domain.ShoppingCar;
import java.math.BigDecimal;

//这里是第一次演示用的
//rule "plan-A" when
//      $shoppingCar:ShoppingCar($foods:buyList)
//      List(size==3) from collect(Food((["巨无霸","可乐","薯条"] contains name)) from $foods)
//  then
//    $shoppingCar.setTotalMoney(17D);
//    $shoppingCar.getRules().add(drools.getRule().getName());
//end

rule "没有套餐"
  salience -1
  no-loop true
  lock-on-active true
  agenda-group "foods_combine"
  when
       $shoppingCar:ShoppingCar($foods:leftList)
       $money:BigDecimal() from accumulate(Food($price:price) from $foods,
             init(BigDecimal total = BigDecimal.ZERO;),
             action(total.subtract($price);),
             result(total))
  then
        $foods.removeAll($foods);
        BigDecimal $totalMoney = $shoppingCar.getTotalMoney().add($money);
        $shoppingCar.setTotalMoney($totalMoney);
        $shoppingCar.getRules().add(drools.getRule().getName());
        update($shoppingCar);
end

