package rules;
import com.study.droolscore.domain.ShoppingCar;
import com.study.droolscore.utils.DateUtils;
import java.util.Date
import java.math.BigDecimal;

rule "周一活动"
    salience -2
    no-loop true
    lock-on-active true
    when
        $shoppingCar:ShoppingCar(DateUtils.checkWeekDay(createTime,2))
    then
        BigDecimal $totalMoney = $shoppingCar.getTotalMoney().multiply(new BigDecimal(0.85D));
        $shoppingCar.setTotalMoney($totalMoney);
        $shoppingCar.getRules().add(drools.getRule().getName());
        //这里可以演示一下update的效果
//        update($shoppingCar);
end

